// HSK1 vocabulary with Vietnamese translations
const HSK1_VOCABULARY = [
  { hanzi: "爱", pinyin: "ài", vietnamese: "yêu, thích" },
  { hanzi: "八", pinyin: "bā", vietnamese: "số tám" },
  { hanzi: "爸爸", pinyin: "bàba", vietnamese: "bố, ba" },
  { hanzi: "杯子", pinyin: "bēizi", vietnamese: "cái cốc" },
  { hanzi: "北京", pinyin: "Běijīng", vietnamese: "Bắc Kinh" },
  { hanzi: "本", pinyin: "běn", vietnamese: "quyển (lượng từ sách)" },
  { hanzi: "不", pinyin: "bù", vietnamese: "không" },
  { hanzi: "不客气", pinyin: "bú kèqi", vietnamese: "không có gì, đừng khách sáo" },
  { hanzi: "菜", pinyin: "cài", vietnamese: "món ăn, rau" },
  { hanzi: "茶", pinyin: "chá", vietnamese: "trà" },
  { hanzi: "吃", pinyin: "chī", vietnamese: "ăn" },
  { hanzi: "出租车", pinyin: "chūzūchē", vietnamese: "taxi" },
  { hanzi: "打电话", pinyin: "dǎ diànhuà", vietnamese: "gọi điện thoại" },
  { hanzi: "大", pinyin: "dà", vietnamese: "lớn, to" },
  { hanzi: "的", pinyin: "de", vietnamese: "của (trợ từ sở hữu)" },
  { hanzi: "点", pinyin: "diǎn", vietnamese: "giờ, điểm" },
  { hanzi: "电脑", pinyin: "diànnǎo", vietnamese: "máy tính" },
  { hanzi: "电视", pinyin: "diànshì", vietnamese: "tivi" },
  { hanzi: "电影", pinyin: "diànyǐng", vietnamese: "phim" },
  { hanzi: "东西", pinyin: "dōngxi", vietnamese: "đồ vật" },
  { hanzi: "都", pinyin: "dōu", vietnamese: "đều, cả" },
  { hanzi: "读", pinyin: "dú", vietnamese: "đọc" },
  { hanzi: "对不起", pinyin: "duìbuqǐ", vietnamese: "xin lỗi" },
  { hanzi: "多", pinyin: "duō", vietnamese: "nhiều" },
  { hanzi: "多少", pinyin: "duōshao", vietnamese: "bao nhiêu" },
  { hanzi: "儿子", pinyin: "érzi", vietnamese: "con trai" },
  { hanzi: "二", pinyin: "èr", vietnamese: "số hai" },
  { hanzi: "饭店", pinyin: "fàndiàn", vietnamese: "nhà hàng, khách sạn" },
  { hanzi: "飞机", pinyin: "fēijī", vietnamese: "máy bay" },
  { hanzi: "分钟", pinyin: "fēnzhōng", vietnamese: "phút" },
  { hanzi: "高兴", pinyin: "gāoxìng", vietnamese: "vui, hạnh phúc" },
  { hanzi: "个", pinyin: "gè", vietnamese: "cái, chiếc (lượng từ)" },
  { hanzi: "工作", pinyin: "gōngzuò", vietnamese: "công việc, làm việc" },
  { hanzi: "狗", pinyin: "gǒu", vietnamese: "con chó" },
  { hanzi: "汉语", pinyin: "Hànyǔ", vietnamese: "tiếng Trung" },
  { hanzi: "好", pinyin: "hǎo", vietnamese: "tốt, khỏe" },
  { hanzi: "号", pinyin: "hào", vietnamese: "số, ngày" },
  { hanzi: "喝", pinyin: "hē", vietnamese: "uống" },
  { hanzi: "和", pinyin: "hé", vietnamese: "và, với" },
  { hanzi: "很", pinyin: "hěn", vietnamese: "rất" },
  { hanzi: "后面", pinyin: "hòumiàn", vietnamese: "phía sau" },
  { hanzi: "回", pinyin: "huí", vietnamese: "về, quay lại" },
  { hanzi: "会", pinyin: "huì", vietnamese: "biết, sẽ" },
  { hanzi: "几", pinyin: "jǐ", vietnamese: "mấy" },
  { hanzi: "家", pinyin: "jiā", vietnamese: "nhà, gia đình" },
  { hanzi: "叫", pinyin: "jiào", vietnamese: "gọi, tên là" },
  { hanzi: "今天", pinyin: "jīntiān", vietnamese: "hôm nay" },
  { hanzi: "九", pinyin: "jiǔ", vietnamese: "số chín" },
  { hanzi: "开", pinyin: "kāi", vietnamese: "mở, lái (xe)" },
  { hanzi: "看", pinyin: "kàn", vietnamese: "xem, nhìn" },
  { hanzi: "看见", pinyin: "kànjiàn", vietnamese: "nhìn thấy" },
  { hanzi: "块", pinyin: "kuài", vietnamese: "đồng (tiền), miếng" },
  { hanzi: "来", pinyin: "lái", vietnamese: "đến" },
  { hanzi: "老师", pinyin: "lǎoshī", vietnamese: "thầy/cô giáo" },
  { hanzi: "了", pinyin: "le", vietnamese: "rồi (trợ từ)" },
  { hanzi: "两", pinyin: "liǎng", vietnamese: "hai, cặp" },
  { hanzi: "冷", pinyin: "lěng", vietnamese: "lạnh" },
  { hanzi: "里", pinyin: "lǐ", vietnamese: "trong" },
  { hanzi: "六", pinyin: "liù", vietnamese: "số sáu" },
  { hanzi: "妈妈", pinyin: "māma", vietnamese: "mẹ, má" },
  { hanzi: "吗", pinyin: "ma", vietnamese: "không? (câu hỏi)" },
  { hanzi: "买", pinyin: "mǎi", vietnamese: "mua" },
  { hanzi: "猫", pinyin: "māo", vietnamese: "con mèo" },
  { hanzi: "没关系", pinyin: "méi guānxi", vietnamese: "không sao đâu" },
  { hanzi: "没有", pinyin: "méiyǒu", vietnamese: "không có" },
  { hanzi: "米饭", pinyin: "mǐfàn", vietnamese: "cơm" },
  { hanzi: "名字", pinyin: "míngzi", vietnamese: "tên" },
  { hanzi: "明天", pinyin: "míngtiān", vietnamese: "ngày mai" },
  { hanzi: "哪", pinyin: "nǎ", vietnamese: "nào" },
  { hanzi: "哪儿", pinyin: "nǎr", vietnamese: "ở đâu" },
  { hanzi: "那", pinyin: "nà", vietnamese: "đó, kia" },
  { hanzi: "呢", pinyin: "ne", vietnamese: "nhỉ, vậy (trợ từ)" },
  { hanzi: "能", pinyin: "néng", vietnamese: "có thể" },
  { hanzi: "你", pinyin: "nǐ", vietnamese: "bạn" },
  { hanzi: "年", pinyin: "nián", vietnamese: "năm" },
  { hanzi: "女儿", pinyin: "nǚ'ér", vietnamese: "con gái" },
  { hanzi: "朋友", pinyin: "péngyou", vietnamese: "bạn bè" },
  { hanzi: "漂亮", pinyin: "piàoliang", vietnamese: "đẹp" },
  { hanzi: "苹果", pinyin: "píngguǒ", vietnamese: "quả táo" },
  { hanzi: "七", pinyin: "qī", vietnamese: "số bảy" },
  { hanzi: "前面", pinyin: "qiánmiàn", vietnamese: "phía trước" },
  { hanzi: "钱", pinyin: "qián", vietnamese: "tiền" },
  { hanzi: "请", pinyin: "qǐng", vietnamese: "xin mời, làm ơn" },
  { hanzi: "去", pinyin: "qù", vietnamese: "đi" },
  { hanzi: "热", pinyin: "rè", vietnamese: "nóng" },
  { hanzi: "人", pinyin: "rén", vietnamese: "người" },
  { hanzi: "认识", pinyin: "rènshi", vietnamese: "quen biết" },
  { hanzi: "三", pinyin: "sān", vietnamese: "số ba" },
  { hanzi: "商店", pinyin: "shāngdiàn", vietnamese: "cửa hàng" },
  { hanzi: "上", pinyin: "shàng", vietnamese: "trên, lên" },
  { hanzi: "上午", pinyin: "shàngwǔ", vietnamese: "buổi sáng" },
  { hanzi: "少", pinyin: "shǎo", vietnamese: "ít" },
  { hanzi: "谁", pinyin: "shéi", vietnamese: "ai" },
  { hanzi: "什么", pinyin: "shénme", vietnamese: "cái gì" },
  { hanzi: "十", pinyin: "shí", vietnamese: "số mười" },
  { hanzi: "时候", pinyin: "shíhou", vietnamese: "lúc, khi" },
  { hanzi: "是", pinyin: "shì", vietnamese: "là" },
  { hanzi: "书", pinyin: "shū", vietnamese: "sách" },
  { hanzi: "水", pinyin: "shuǐ", vietnamese: "nước" },
  { hanzi: "水果", pinyin: "shuǐguǒ", vietnamese: "trái cây" },
  { hanzi: "睡觉", pinyin: "shuìjiào", vietnamese: "ngủ" },
  { hanzi: "说", pinyin: "shuō", vietnamese: "nói" },
  { hanzi: "四", pinyin: "sì", vietnamese: "số bốn" },
  { hanzi: "岁", pinyin: "suì", vietnamese: "tuổi" },
  { hanzi: "他", pinyin: "tā", vietnamese: "anh ấy" },
  { hanzi: "她", pinyin: "tā", vietnamese: "cô ấy" },
  { hanzi: "太", pinyin: "tài", vietnamese: "quá, rất" },
  { hanzi: "天气", pinyin: "tiānqì", vietnamese: "thời tiết" },
  { hanzi: "听", pinyin: "tīng", vietnamese: "nghe" },
  { hanzi: "同学", pinyin: "tóngxué", vietnamese: "bạn học" },
  { hanzi: "喂", pinyin: "wèi", vietnamese: "alo (gọi điện)" },
  { hanzi: "我", pinyin: "wǒ", vietnamese: "tôi" },
  { hanzi: "我们", pinyin: "wǒmen", vietnamese: "chúng tôi" },
  { hanzi: "五", pinyin: "wǔ", vietnamese: "số năm" },
  { hanzi: "喜欢", pinyin: "xǐhuan", vietnamese: "thích" },
  { hanzi: "下", pinyin: "xià", vietnamese: "dưới, xuống" },
  { hanzi: "下午", pinyin: "xiàwǔ", vietnamese: "buổi chiều" },
  { hanzi: "下雨", pinyin: "xià yǔ", vietnamese: "mưa" },
  { hanzi: "先生", pinyin: "xiānshēng", vietnamese: "ông, thầy" },
  { hanzi: "现在", pinyin: "xiànzài", vietnamese: "bây giờ" },
  { hanzi: "想", pinyin: "xiǎng", vietnamese: "muốn, nghĩ" },
  { hanzi: "小", pinyin: "xiǎo", vietnamese: "nhỏ, bé" },
  { hanzi: "小姐", pinyin: "xiǎojiě", vietnamese: "cô, chị" },
  { hanzi: "些", pinyin: "xiē", vietnamese: "một số" },
  { hanzi: "写", pinyin: "xiě", vietnamese: "viết" },
  { hanzi: "谢谢", pinyin: "xièxie", vietnamese: "cảm ơn" },
  { hanzi: "星期", pinyin: "xīngqī", vietnamese: "tuần, thứ" },
  { hanzi: "学生", pinyin: "xuésheng", vietnamese: "học sinh" },
  { hanzi: "学习", pinyin: "xuéxí", vietnamese: "học tập" },
  { hanzi: "学校", pinyin: "xuéxiào", vietnamese: "trường học" },
  { hanzi: "一", pinyin: "yī", vietnamese: "số một" },
  { hanzi: "衣服", pinyin: "yīfu", vietnamese: "quần áo" },
  { hanzi: "医生", pinyin: "yīshēng", vietnamese: "bác sĩ" },
  { hanzi: "医院", pinyin: "yīyuàn", vietnamese: "bệnh viện" },
  { hanzi: "椅子", pinyin: "yǐzi", vietnamese: "cái ghế" },
  { hanzi: "有", pinyin: "yǒu", vietnamese: "có" },
  { hanzi: "月", pinyin: "yuè", vietnamese: "tháng, mặt trăng" },
  { hanzi: "再见", pinyin: "zàijiàn", vietnamese: "tạm biệt" },
  { hanzi: "在", pinyin: "zài", vietnamese: "ở, đang" },
  { hanzi: "怎么", pinyin: "zěnme", vietnamese: "như thế nào" },
  { hanzi: "怎么样", pinyin: "zěnmeyàng", vietnamese: "thế nào, ra sao" },
  { hanzi: "这", pinyin: "zhè", vietnamese: "này, đây" },
  { hanzi: "中国", pinyin: "Zhōngguó", vietnamese: "Trung Quốc" },
  { hanzi: "中午", pinyin: "zhōngwǔ", vietnamese: "buổi trưa" },
  { hanzi: "住", pinyin: "zhù", vietnamese: "sống, ở" },
  { hanzi: "桌子", pinyin: "zhuōzi", vietnamese: "cái bàn" },
  { hanzi: "字", pinyin: "zì", vietnamese: "chữ" },
  { hanzi: "昨天", pinyin: "zuótiān", vietnamese: "hôm qua" },
  { hanzi: "做", pinyin: "zuò", vietnamese: "làm" },
  { hanzi: "坐", pinyin: "zuò", vietnamese: "ngồi" },
  { hanzi: "庞立亮", pinyin: "Páng Lìliàng", vietnamese: "Pang Liliang (người tặng quà)" },
  { hanzi: "卢氏芳", pinyin: "Lú Shìfāng", vietnamese: "Lò Thị Phương (đẹp gái)" }
];
